### PR TITLE
New boursorama website

### PR DESCRIPTION
**Pull request by Glandos**
Better PR than #8

### CODE REVIEW

**Comment by Glandos** [comment]
Thanks. Can you also update it on https://openuserjs.org/scripts/bouil/Boursorama_-_No_Virtual_Keyboard ?

**Comment by bouil** [comment]
Of course, if you can send me the built script. I've not the build environement at hand.
Thanks.

**Comment by Glandos** [comment]
Here you are: https://gist.github.com/Glandos/61eb3bd16cb8aaf4827b89955c2f4b23

**Comment by bouil** [comment]
Done. Thank you.

**Pull request merged**
